name: flutter_cljd
description: "ClojureDart wrapper on Flutter widgets."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.2+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  visibility_detector: ^0.4.0+2
  flutter_highlight: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  test: ^1.26.3

flutter:
  uses-material-design: true
